apiVersion: v1
kind: Service
metadata:
  name: sentinel-gateway-service
spec:
  type: LoadBalancer # This creates a public IP in the cloud
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: sentinel-gateway